const ATTRIBUTES = {
  ENABLE_HANDICAPPED_VEHICLES: 'ENABLE_HANDICAPPED_VEHICLES',
  ENABLE_COMPANY_LOYALTIES: 'ENABLE_COMPANY_LOYALTIES',
  KIOSK_SEQ_N: 'KIOSK_SEQ_N',
  KIOSK_CLOSE_SALES_IN_X_MINUTES_BEFORE_DEPARTURE: 'KIOSK_CLOSE_SALES_IN_X_MINUTES_BEFORE_DEPARTURE',
  KIOSK_TERMS_PREFIX: 'KIOSK_TERMS_',
  KIOSK_TERMS_EN: [
    'Ticket purchased from the ticket machine cannot be changed or cancelled.',
    'Ticket is only valid on the departure marked on it.',
    'Ticket must be maintained at least until the end of trip.',
    'Ticket sale and boarding ends 5 minutes before departure.',
  ],
  KIOSK_SOLD_OUT_INFO_PREFIX: 'KIOSK_SOLD_OUT_INFO_',
  KIOSK_SOLD_OUT_INFO_PART_ONE: 'KIOSK_SOLD_OUT_INFO_PART_ONE',
  KIOSK_COEFFICIENTS_PREFIX: 'CARDECK_',
  KIOSK_COEFFICIENTS_HEADER: '_HEADER',
  KIOSK_COEFFICIENTS_WIDTH: '_WIDTH',
  KIOSK_COEFFICIENTS_HEIGHT: '_HEIGHT',
  KIOSK_SOLD_OUT_INFO_RESIDENT: 'KIOSK_SOLD_OUT_INFO_RESIDENT',
  SHOW_ADULT_TICKET_LOCAL_INVENTORY_USAGE: 'SHOW_ADULT_TICKET_LOCAL_INVENTORY_USAGE',
}
export default ATTRIBUTES
