const PAYMENT_STATUS = {
  INITIAL: 'INITIAL',
  STARTED: 'PAYMENT_REQUEST_STARTED',
  READ_OK: 'PAYMENT_REQUEST_READ_OK',
  SUCCESS: 'PAYMENT_REQUEST_SUCCESS',
  FAILED: 'PAYMENT_REQUEST_FAILED',
  FAILED_TIMEOUT: 'PAYMENT_REQUEST_FAILED_TIMEOUT',
  FAILED_CANCELLED: 'PAYMENT_REQUEST_FAILED_CANCELLED',
  TRANSACTION_FAILED: 'PAYMENT_REQUEST_TRANSACTION_FAILED',
  PRINT_STARTED: 'PAYMENT_REQUEST_RECEIPT_PRINT_STARTED',
  PRINT_OK: 'PAYMENT_REQUEST_RECEIPT_PRINT_OK',
  PRINT_FAILED: 'PAYMENT_REQUEST_RECEIPT_PRINT_FAILED',
  CONNECT_FAILED: 'CONNECT_FAILED',
  PAYMENT_TERMINAL_CONNECT_FAILED: 'PAYMENT_TERMINAL_CONNECT_FAILED',
  INVALID_RESERVATION_STATUS: 'INVALID_RESERVATION_STATUS',
  UNKNOWN: 'UNKNOWN',
}
export default PAYMENT_STATUS
