const TICKET_TYPE = {
  CITIZEN: 'citizen',
  VEHICLE: 'vehicle',
  TRAILER: 'trailer',
  CAR: 'Car',
  PASSENGER: 'Passenger',
  BICYCLE: 'bicycle',
  VISUALLY_IMPAIRED_PERSON: 'VISUALLY_IMPAIRED_PERSON',
  ACCOMPANYING_PERSON: 'ACCOMPANYING_PERSON',
  PERSON: 'PERSON',
  RESIDENT: 'RESIDENT',
  HANDICAPPED_PERSON: 'HANDICAPPED_PERSON',
}
export default TICKET_TYPE
